name: Delivery-Diff Pods 2-4


on:
  workflow_dispatch:
    inputs:
      egp_file:
        description: "Relative path of the .egp file to diff"
        required: true
      source_folder:
        description: "The source folder to diff"
        required: true


jobs:
  folder-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get-install unzip

      - name: Unzip .egp file
        run: |
          EGP_FILE="${{ github.event.inputs.egp_file }}"
          unzip $EGP_FILE -d ./egp_file_contents

      - name: Diff
        run: |
          echo "Running diff..."
          SOURCE_FOLDER="${{ github.event.inputs.source_folder }}"
          diff -r $SOURCE_FOLDER ./egp_file_contents || true
          echo "Diff complete."
